[build]
  publish = "./"
  
[[redirects]]
  from = "/api/*"
  to = "https://yvix-assignment-portal.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"} 